import Head from 'next/head';
import { useState } from 'react';
import { FiHelpCircle } from 'react-icons/fi';
import SplineViewer from '@/Spline';

export default function Home() {
  const [isOverlayOpen, setIsOverlayOpen] = useState(false);

  const toggleOverlay = () => {
    setIsOverlayOpen(!isOverlayOpen);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app-container">
        <SplineViewer />

        <div className="nav-icon" onClick={toggleOverlay}>
          <FiHelpCircle size={50} color="white" />
        </div>

        {isOverlayOpen && (
          <>
            <div className="overlay-content">
              <h2>Overlay Title</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
                nec odio. Praesent libero. Sed cursus ante dapibus diam.
              </p>
              <p>
                Suspendisse potenti. Nulla facilisi. Nulla quis sem at nibh
                elementum imperdiet.
              </p>
            </div>

            <div className="blur-background" onClick={toggleOverlay}></div>
          </>
        )}
      </div>
    </>
  );
}
